# 미래에 필요 시 레디스 클러스터와 센티널을 준비하여 연결한다.
spring:
  profiles:
    active: local

  cache:
    type: redis
    redis:
      time-to-live: 600
  redis:
    port: 6379
    
    lettuce:
      shutdown-timeout: 100ms

server:
  error:
    include-message: always
    
logging:
  level:
    root: info
    